"""system parameters

Revision ID: 0003
Revises: 0002
Create Date: 2026-04-21 00:30:00.000000

"""
from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    _ = op.create_table(
        "system_parameters",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "approval",
                "auth",
                "sku",
                "contract",
                "upload",
                "pagination",
                "audit",
                name="systemparametercategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_type", sa.String(length=16), nullable=False),
        sa.Column("default_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("min_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("max_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("description_zh", sa.Text(), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=False),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"]),
        sa.UniqueConstraint("key"),
    )
    op.create_index("ix_system_parameters_category", "system_parameters", ["category"])

    system_parameters = sa.table(
        "system_parameters",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("key", sa.String),
        sa.column(
            "category",
            sa.Enum(
                "approval",
                "auth",
                "sku",
                "contract",
                "upload",
                "pagination",
                "audit",
                name="systemparametercategory",
                native_enum=False,
                length=32,
            ),
        ),
        sa.column("value", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("data_type", sa.String),
        sa.column("default_value", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("min_value", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("max_value", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("unit", sa.String),
        sa.column("description_zh", sa.Text),
        sa.column("description_en", sa.Text),
        sa.column("is_sensitive", sa.Boolean),
        sa.column("updated_by_id", postgresql.UUID(as_uuid=True)),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )

    now = datetime.now(timezone.utc)
    seed_rows = [
        {
            "id": uuid4(),
            "key": "approval.amount_threshold_cny",
            "category": "approval",
            "value": 100000,
            "data_type": "int",
            "default_value": 100000,
            "min_value": 0,
            "max_value": 100000000,
            "unit": "CNY",
            "description_zh": "需要采购经理审批的金额阈值",
            "description_en": "Amount threshold triggering procurement manager approval",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.access_token_expire_minutes",
            "category": "auth",
            "value": 480,
            "data_type": "int",
            "default_value": 480,
            "min_value": 5,
            "max_value": 10080,
            "unit": "minutes",
            "description_zh": "访问令牌有效期",
            "description_en": "Access token TTL",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.refresh_token_expire_days",
            "category": "auth",
            "value": 7,
            "data_type": "int",
            "default_value": 7,
            "min_value": 1,
            "max_value": 90,
            "unit": "days",
            "description_zh": "刷新令牌有效期",
            "description_en": "Refresh token TTL",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.download_token_ttl_seconds",
            "category": "auth",
            "value": 3600,
            "data_type": "int",
            "default_value": 3600,
            "min_value": 60,
            "max_value": 86400,
            "unit": "seconds",
            "description_zh": "文件下载令牌有效期",
            "description_en": "Download token TTL",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "sku.benchmark_window_days",
            "category": "sku",
            "value": 90,
            "data_type": "int",
            "default_value": 90,
            "min_value": 7,
            "max_value": 730,
            "unit": "days",
            "description_zh": "SKU 基准价统计窗口",
            "description_en": "SKU benchmark calculation window",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "sku.anomaly_threshold_pct",
            "category": "sku",
            "value": 20,
            "data_type": "int",
            "default_value": 20,
            "min_value": 1,
            "max_value": 100,
            "unit": "%",
            "description_zh": "SKU 价格异常阈值 (±%)",
            "description_en": "SKU price anomaly threshold (±%)",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "sku.sample_size_min",
            "category": "sku",
            "value": 3,
            "data_type": "int",
            "default_value": 3,
            "min_value": 1,
            "max_value": 100,
            "unit": "count",
            "description_zh": "基准价最小样本数",
            "description_en": "Minimum samples for benchmark",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "sku.critical_multiplier",
            "category": "sku",
            "value": 2,
            "data_type": "float",
            "default_value": 2,
            "min_value": 1.0,
            "max_value": 10.0,
            "unit": "x",
            "description_zh": "价格异常严重级别倍数 (warning × n = critical)",
            "description_en": "Critical anomaly multiplier",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "sku.price_trend_window_days",
            "category": "sku",
            "value": 180,
            "data_type": "int",
            "default_value": 180,
            "min_value": 30,
            "max_value": 1095,
            "unit": "days",
            "description_zh": "SKU 价格趋势回看窗口",
            "description_en": "Price trend lookback window",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "contract.expiry_reminder_days",
            "category": "contract",
            "value": 30,
            "data_type": "int",
            "default_value": 30,
            "min_value": 1,
            "max_value": 365,
            "unit": "days",
            "description_zh": "合同到期提醒提前天数",
            "description_en": "Contract expiry reminder window",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "upload.max_file_size_bytes",
            "category": "upload",
            "value": 10485760,
            "data_type": "int",
            "default_value": 10485760,
            "min_value": 1048576,
            "max_value": 104857600,
            "unit": "bytes",
            "description_zh": "最大上传文件大小",
            "description_en": "Maximum upload file size",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "upload.chunk_size_bytes",
            "category": "upload",
            "value": 1048576,
            "data_type": "int",
            "default_value": 1048576,
            "min_value": 65536,
            "max_value": 10485760,
            "unit": "bytes",
            "description_zh": "文件流式读取分块大小",
            "description_en": "File streaming chunk size",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "pagination.default_page_size",
            "category": "pagination",
            "value": 50,
            "data_type": "int",
            "default_value": 50,
            "min_value": 10,
            "max_value": 500,
            "unit": "count",
            "description_zh": "默认分页大小",
            "description_en": "Default page size",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "audit.default_lookback_days",
            "category": "audit",
            "value": 7,
            "data_type": "int",
            "default_value": 7,
            "min_value": 1,
            "max_value": 365,
            "unit": "days",
            "description_zh": "审计日志默认查询窗口",
            "description_en": "Audit log default lookback window",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
    ]
    op.bulk_insert(system_parameters, seed_rows)


def downgrade() -> None:
    op.drop_index("ix_system_parameters_category", table_name="system_parameters")
    op.drop_table("system_parameters")
