"""seed saml system parameters

Revision ID: 0013
Revises: 0012
Create Date: 2026-04-23
"""

from datetime import UTC, datetime
from uuid import uuid4

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


def upgrade() -> None:
    system_parameters = sa.table(
        "system_parameters",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("key", sa.String),
        sa.column(
            "category",
            sa.Enum(
                "approval",
                "auth",
                "sku",
                "contract",
                "upload",
                "pagination",
                "audit",
                name="systemparametercategory",
                native_enum=False,
                length=32,
            ),
        ),
        sa.column("value", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("data_type", sa.String),
        sa.column("default_value", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("min_value", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("max_value", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("unit", sa.String),
        sa.column("description_zh", sa.Text),
        sa.column("description_en", sa.Text),
        sa.column("is_sensitive", sa.Boolean),
        sa.column("updated_by_id", postgresql.UUID(as_uuid=True)),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )

    now = datetime.now(UTC)
    rows = [
        {
            "id": uuid4(),
            "key": "auth.saml.enabled",
            "category": "auth",
            "value": False,
            "data_type": "bool",
            "default_value": False,
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "启用 SAML / ADFS 单点登录",
            "description_en": "Enable SAML / ADFS single sign-on",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.idp.entity_id",
            "category": "auth",
            "value": "",
            "data_type": "string",
            "default_value": "",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML IdP 实体 ID",
            "description_en": "SAML IdP entity ID",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.idp.sso_url",
            "category": "auth",
            "value": "",
            "data_type": "string",
            "default_value": "",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML IdP 单点登录 URL",
            "description_en": "SAML IdP single sign-on URL",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.idp.slo_url",
            "category": "auth",
            "value": "",
            "data_type": "string",
            "default_value": "",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML IdP 单点登出 URL（可选）",
            "description_en": "SAML IdP single logout URL (optional)",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.idp.x509_cert",
            "category": "auth",
            "value": "",
            "data_type": "string",
            "default_value": "",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML IdP X.509 证书",
            "description_en": "SAML IdP X.509 certificate",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.sp.entity_id",
            "category": "auth",
            "value": "",
            "data_type": "string",
            "default_value": "",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML 服务提供者实体 ID（留空则自动推导）",
            "description_en": "SAML service provider entity ID (leave empty to auto-derive)",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.sp.acs_url",
            "category": "auth",
            "value": "",
            "data_type": "string",
            "default_value": "",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML ACS 回调地址（留空则自动推导）",
            "description_en": "SAML ACS callback URL (leave empty to auto-derive)",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.attr.email",
            "category": "auth",
            "value": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
            "data_type": "string",
            "default_value": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML 邮箱属性名",
            "description_en": "SAML email attribute name",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.attr.display_name",
            "category": "auth",
            "value": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
            "data_type": "string",
            "default_value": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML 显示名属性名",
            "description_en": "SAML display-name attribute name",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.attr.groups",
            "category": "auth",
            "value": "http://schemas.xmlsoap.org/claims/group",
            "data_type": "string",
            "default_value": "http://schemas.xmlsoap.org/claims/group",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML 用户组属性名",
            "description_en": "SAML group attribute name",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.jit.enabled",
            "category": "auth",
            "value": True,
            "data_type": "bool",
            "default_value": True,
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "允许 SAML 首次登录自动创建用户",
            "description_en": "Allow just-in-time user provisioning for first-time SAML logins",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.jit.default_role",
            "category": "auth",
            "value": "requester",
            "data_type": "string",
            "default_value": "requester",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML 自动创建用户的默认角色",
            "description_en": "Default role for JIT-provisioned SAML users",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.jit.default_company_code",
            "category": "auth",
            "value": "DEMO",
            "data_type": "string",
            "default_value": "DEMO",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML 自动创建用户的默认公司编码",
            "description_en": "Default company code for JIT-provisioned SAML users",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.jit.default_department_code",
            "category": "auth",
            "value": "",
            "data_type": "string",
            "default_value": "",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML 自动创建用户的默认部门编码（可选）",
            "description_en": "Default department code for JIT-provisioned SAML users (optional)",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.group_mapping_enabled",
            "category": "auth",
            "value": False,
            "data_type": "bool",
            "default_value": False,
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "启用 SAML 用户组到本地角色的自动映射",
            "description_en": "Enable automatic mapping from SAML groups to local roles",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "key": "auth.saml.group_mapping",
            "category": "auth",
            "value": "[]",
            "data_type": "string",
            "default_value": "[]",
            "min_value": None,
            "max_value": None,
            "unit": None,
            "description_zh": "SAML 用户组映射 JSON（按顺序匹配）",
            "description_en": "SAML group mapping JSON (matched in order)",
            "is_sensitive": False,
            "updated_by_id": None,
            "created_at": now,
            "updated_at": now,
        },
    ]
    op.bulk_insert(system_parameters, rows)


def downgrade() -> None:
    op.execute(
        sa.text(
            "DELETE FROM system_parameters WHERE key LIKE 'auth.saml.%' OR key = 'auth.saml.group_mapping_enabled'"
        )
    )
